language: python
python:
- 3.6
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: abhishekray07
  password:
    secure: x4z6u2lOh4XVib2nB1/1vcpp1iqmMeVLAc0SraM9vCdfuHCCWM/WvE2PXzFUPbjZQKU1p7JNm+e3WW6ssSGoAkNL5nBOW/cGgSZtKQWvjS3DAXdQYcY2zNCKsbThgJBb4HZXB2VmldVfW/tsTsWtMb4zCEZGzolAteV/iHeOvrahZGlWas+q1+OP9Ho5unYqpwyEil+QqmC493ilZqV8AaUzC4EbBxeeZ5jXJTeayj9o1KCoqckPoHilpHm3VBTDETiiHi05UIyM+hvAeB+vdTvA/nE0P2sjv3tcB/MyBTsyWnCmjYOujsnZskswEDNQfoek0536smE0tAKUDyn0qAROnunS8r/KknMKlbJgr4Ilq3bgZMIxEQlf4yPIJPxf+tiVMIrw+vfS+jN2uXHeSYD6b58LPqB6+vpoeyGepOsX6Jdv/3DXASUIOw/Trt+Zb/I63gbTgep6CZDodbmGYmxBvnmMZTzUNfobRWlNevntnXBlrA2FaXo1lZfUPuiewpx+nsqYHuNtc9g9pleBk3q8iEbBy4e+7co+Etmh1x6lES8LA/4DhsTPTBlWjvxfs1H8fc/tCGVPo7CBIMKuRHGs25rm9nDTD4GGDJTrKVshoCtt49+rSUncvpEJ0V+JtOVy6jP6lbv55GXpK0DGdxgrj0QVb17btVBFk2fKG8k=
  on:
    tags: true
    repo: abhishekray07/kq
    python: 3.6
